/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package CuaHang;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.ArrayList;
import java.util.Scanner;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lenovo
 */
public class Hang_Hoa extends javax.swing.JFrame {

    private DefaultTableModel tabelModel;
    private ArrayList<HangHoa> dsHH;
    private ArrayList<DienThoai> dsDT;
    private ArrayList<MayTinhBang> dsMTB;

    public Hang_Hoa() {
        initComponents();
        tabelModel = (DefaultTableModel) tbl.getModel();
        dsDT = new ArrayList<>();
        dsMTB = new ArrayList<>();
        dsHH = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        find = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tên hàng", "Mã hàng", "Giá nhập", "Giá bán", "Giá sim ghép", "Kích thước màn hình", "Lợi nhuận"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl);

        jButton1.setText("Đọc");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Nhập mã hàng cần tìm kiếm");

        jButton2.setText("Tìm kiếm");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jButton1))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(109, 109, 109)
                                .addComponent(find, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(206, 206, 206)
                                .addComponent(jButton2)))
                        .addGap(0, 36, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(find, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(93, 93, 93))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            File f = new File("hanghoa.txt");
            Scanner sc = new Scanner(f);

            while (sc.hasNextLine()) {
                String[] data = sc.nextLine().split("\\$");

                if (data[5].compareTo("0") == 0) {
                    DienThoai dt = new DienThoai();

                    dt.setTenHang(data[0]);
                    dt.setMaHang(data[1]);
                    dt.setGiaNhap(Double.parseDouble(data[2]));
                    dt.setGiaBan(Double.parseDouble(data[3]));
                    dt.setGiaSimGhep(Double.parseDouble(data[4]));

                    dsDT.add(dt);

                }

                if (data[4].compareTo("0") == 0) {
                    MayTinhBang mtb = new MayTinhBang();

                    mtb.setTenHang(data[0]);
                    mtb.setMaHang(data[1]);
                    mtb.setGiaNhap(Double.parseDouble(data[2]));
                    mtb.setGiaBan(Double.parseDouble(data[3]));
                    mtb.setKichThuocManHinh(data[5]);

                    dsMTB.add(mtb);
                }
            }

            for (DienThoai d : dsDT) {
                Object[] row = new Object[]{
                    d.getTenHang(), d.getMaHang(), d.getGiaNhap(),
                    d.getGiaBan(), d.getGiaSimGhep(), null, d.loiNhuan()
                };
                tabelModel.addRow(row);
                tabelModel.fireTableDataChanged();
            }

            for (MayTinhBang m : dsMTB) {
                Object[] row = new Object[]{
                    m.getTenHang(), m.getMaHang(), m.getGiaNhap(),
                    m.getGiaBan(), null, m.getKichThuocManHinh(), m.loiNhuan()
                };
                tabelModel.addRow(row);
                tabelModel.fireTableDataChanged();
            }

        } catch (FileNotFoundException ex) {
            Logger.getLogger(Hang_Hoa.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            File f = new File("hanghoa.txt");
            Scanner sc = new Scanner(f);

            while (sc.hasNextLine()) {
                String[] data = sc.nextLine().split("\\$");

                if (data[5].compareTo("0") == 0) {
                    DienThoai dt = new DienThoai();

                    dt.setTenHang(data[0]);
                    dt.setMaHang(data[1]);
                    dt.setGiaNhap(Double.parseDouble(data[2]));
                    dt.setGiaBan(Double.parseDouble(data[3]));
                    dt.setGiaSimGhep(Double.parseDouble(data[4]));

                    dsHH.add(dt);

                }

                if (data[4].compareTo("0") == 0) {
                    MayTinhBang mtb = new MayTinhBang();

                    mtb.setTenHang(data[0]);
                    mtb.setMaHang(data[1]);
                    mtb.setGiaNhap(Double.parseDouble(data[2]));
                    mtb.setGiaBan(Double.parseDouble(data[3]));
                    mtb.setKichThuocManHinh(data[5]);

                    dsHH.add(mtb);
                }
            }
            
            for( HangHoa hh : dsHH ){
                if( hh.getMaHang().compareTo(find.getText()) == 0){
                    hh.toString();
                }
            }
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Hang_Hoa.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hang_Hoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hang_Hoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hang_Hoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hang_Hoa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hang_Hoa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField find;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables
}
